fix,test(infra): Simple token fix
Shift3/boilerplate-client-angular pull request #383
Opened 2022-02-07 21:24 UTC by pratimasakinala

## Changes
  1. Renames token field to match server. 
  2. Refactors services to use the new name.

## Purpose
To make the client work with the changes from [PR 369](https://github.com/Shift3/boilerplate-server-node/pull/369).

## Approach
This uses the token field now returned by the server and ensures the user can stay logged in by not running JWT-specific checks on the token.

## Learning
The fix that was implemented on [React BP](https://github.com/Shift3/boilerplate-client-react/pull/518) for this.

Closes #382

2022-02-07 21:40 UTC, DropsOfSerenity requested changes
Pretty straightforward, but you left a `debugger` statement in xD

2022-02-07 21:40 UTC, DropsOfSerenity commented on src/app/infrastructure/core/services/state/user-state.service.ts
> +    debugger;
Probably want to remove this :smile:

2022-02-07 21:40 UTC, pratimasakinala commented on src/app/infrastructure/core/services/state/user-state.service.ts
> +    debugger;
good catch! 🤦‍♀️

2022-03-10 17:02 UTC, michaelachrisco approved these changes
Are we waiting on anything on this? Code looks good.

2022-08-30 21:43 UTC, merged